### PR TITLE
remove ssl from maestro conf

### PR DESCRIPTION
**Pull request by psppalash**
This PR addresses the following:
New identity.json will not have ssl section. Adapt fsonly platform reader to not parse the ssl certs and also update the maestro conf to not save the certs on filesystem.

### CODE REVIEW

**Comment by costanic** [comment]
why do we need this.  also, please don't link to private jira tickets in GitHub PRs.

**Comment by psppalash** [comment]
> why do we need this. also, please don't link to private jira tickets in GitHub PRs.

FYI, as now fog-proxy utilizes the lwm2m certificate, we will be deprecating the self-signed certificate which is part of identity.json. (Yash's comment)

**Comment by psppalash** [comment]
DO NOT MERGE THIS YET.
Need to change maestro code so that it does not throw error if "ca_chain" is not provided.

**Comment by psppalash** [comment]
Please refer https://jira.arm.com/browse/PELEDGE19-2945?focusedCommentId=4854170&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4854170

Since devicedb is enabled in snap-pelion-edge now, @ygoyal18 @costanic we can merge this PR.
I will test it again on hardware to make sure all the services are up and running with these changes.

**Pull request merged**
