### PR TITLE
Add Clear_address field to clear out addresses from an interface

### PR DESCRIPTION
**Pull request by psppalash**
For the "clear_addresses: true" flag please refer https://jira.arm.com/browse/PELEDGE19-1452

### CODE REVIEW

**Comment by CristianPrundeanuARM** [comment]
Won't this make it so that every restart of maestro will discard any changes made via deviceDB or maestroShell? If so, I don't think it's the behavior we want.

**Comment by ygoyal18** [comment]
@psppalash The config file of any gateway service defines the default set of parameters which are required for the very 1st boot of the service. Service then saves the configuration data into devicedb. From that point onwards, any configuration change required should be made directly to devicedb and not through config file. 

If you want to force the service to ignore or clean up the old configuration saved in devicedb, you should define a command line parameter like --clean or something similar.

**Comment by psppalash** [comment]
@ygoyal18 I have removed the existing field from the conf file

**Comment by CristianPrundeanuARM** [comment]
This is no longer needed. The fix is in [PR 85](https://github.com/armPelionEdge/maestro/pull/85) in maestro.

**Pull request merged**
